utopia-rise/fmod-gdextension

godot_fmod.cpp, godot_fmod.h
This enables Fmod GDNative to play classic music files.
@author : Pierre-Thomas Meisels <piiertho@github.com>
diff --git a/godot_fmod.cpp b/godot_fmod.cpp
index a9176d7..8aff727 100644
--- a/godot_fmod.cpp
+++ b/godot_fmod.cpp
@@ -59,6 +59,16 @@ void GodotFmod::_register_methods() {
register_method("playOneShotAttachedWithParams", &GodotFmod::playOneShotAttachedWithParams);
register_method("attachInstanceToNode", &GodotFmod::attachInstanceToNode);
register_method("detachInstanceFromNode", &GodotFmod::detachInstanceFromNode);
+    register_method("loadSound", &GodotFmod::loadSound);
+    register_method("playSound", &GodotFmod::playSound);
+    register_method("stopSound", &GodotFmod::stopSound);
+    register_method("releaseSound", &GodotFmod::releaseSound);
+ …
=> play-classic-music-files : Added methods to play classic music files

.travis.yml
This provides build configuration for ios on travis.
This enables releases for ios built.
=> Travis ios

README.md, godot_fmod.cpp, godot_fmod.h
This add a new method to set 3D global settings for fmod.
This is a new feature, thus new release should be updated with minor version upgrade.
=> Set 3D sound settings

README.md, godot_fmod.cpp, godot_fmod.h
This get rid of dirty maps to access fmod flags.
=> Remove dirty maps

README.md, godot_fmod.cpp, godot_fmod.h
This optimize event and sounds access by generating a unique id at instantiation. This is a conformity modification with [engine way](https://github.com/alexfonseka/godot-fmod-integration)
=> Auto event instance

godot_fmod.cpp
Banks were not released properly from banks map.
Conform our repo to module version.
=> Hotfix release banks

README.md, godot_fmod.cpp, godot_fmod.h
This moves out several maps to handle event nature, using UserData of EventInstance.
=> User data rework and mute pause helpers

README.md, callbacks.h, gdlibrary.cpp, godot_fmod.cpp, godot_fmod.h
This implements fmod callbacks, with timelines and beats.
=> Event callback

gdlibrary.cpp, godot_fmod.cpp, godot_fmod.h
Move update method to _process, so that we have not to handle it in GDScript.
Check that fmod is initialized at starting of _process.
=> Singleton gd native

demo/Script/Emitter.gd, demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
Ability to get and set event parameters by id or name.
=> Set parameter by ID

demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
This enable to get and set global parameters and their description by name and id.
=> Global params

demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
This add event description api helper methods.
=> Event description api

demo/Script/Listener.gd, demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
Add method to get and set event parameters manually.
=> Manually set event3d attributes

demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
This add methods to set Listener mask on event instance.
=> ListenerMask : Add helper method to set Event listener mask

demo/Scenes/FmodTest.tscn, demo/Scenes/GdScriptTest.tscn, demo/Script/FmodTest.gd, demo/Script/Listener.gd, demo/Script/Listener2.gd, demo/addons/fmod/Fmod.gd, demo/project.godot, src/godot_fmod.cpp, src/godot_fmod.h
New implementation of multiple listeners where the users choose the number he needs.
=> Multiple listeners

.travis.yml
Travis CI linux vm default configs have changed, this fix build failures.
=> Fix linux scons travis

src/godot_fmod.cpp
fix #45 
It was probably my mistake.
=> fix nullptr in shutdown method

demo/Script/Listener.gd, src/godot_fmod.cpp
Add listener lock to fix listener position (can be tested with scene and T key)
=> hotfix/Add Listener Lock

.github/workflows/all_builds.yml, SConstruct
=> Macos universal build

.github/workflows/all_builds.yml, demo/android/fmod/src/FmodSingleton.java
This resolves #114 
This resolves #124
=> fix: remove reference to godot activity in FmodSingleton.java

README.md
=> Include Discord invite URL in README.md

README.md
=> Add Godot compatibility badge

demo/Script/FmodTest.gd, demo/addons/fmod/Fmod.gd, demo/fmod/fmod_config.cfg, demo/project.godot, src/godot_fmod.cpp, src/godot_fmod.h
fix #118 
Simple change of signature
=> Remove unused return type for load_bank()

src/helpers/maths.h
Fix 3D direction of the sound. 
I still needed to add a negative value for the Forward axis despite FMOD being set to right-handed basis so not sure what I'm not understanding it mathematically but otherwise it seems to work.
=> Fix 3D rotation

demo/addons/fmod/libs/macos/libGodotFmod.macos.editor.framework/Info.plist, demo/addons/fmod/libs/macos/libGodotFmod.macos.template_debug.framework/Info.plist, demo/addons/fmod/libs/macos/libGodotFmod.macos.template_release.framework/Info.plist
=> fix: add macos Info.plist to artifacts

src/studio/fmod_event.cpp, src/studio/fmod_event.h
This resolves #186 
This makes this plugin incompatible with FMOD prior to 2.02
=> feat: add methods in FmodEvent to set parameters by label

src/fmod_server.cpp
This disables live update for editor.  
This resolves #236
=> fix: disable live update for editor

demo/addons/fmod/FmodEditorExportPluginProxy.gd, demo/addons/fmod/FmodPlugin.gd
=> chore: remove FmodEditorExportPluginProxy

src/nodes/fmod_event_emitter.h, src/nodes/fmod_listener.h
This resolves #217 
This is the beginning of emitters rework, still a bunch of work to do on them.
=> enh: set parameters within play method. Add method to set parameters by id.

demo/high_level_2D/Kinematic.gd, demo/high_level_2D/SayWelcomeButton.gd, demo/high_level_2D/footstep.tscn, src/nodes/fmod_event_emitter.h, src/nodes/fmod_event_emitter_2d.cpp, src/nodes/fmod_event_emitter_2d.h, src/nodes/fmod_event_emitter_3d.cpp, src/nodes/fmod_event_emitter_3d.h
This adds `play_one_shot` method to emitters.
=> feat: Add play_one_shot method to emitters

src/nodes/fmod_event_emitter.h
This enables to restart event if it is playing.
=> feat: enable to restart event when calling play

src/nodes/fmod_event_emitter.h
This makes preload_event option to load event if true.
=> feat: load event when preload_event option is true

demo/addons/fmod/tool/inspectors/FmodBankLoaderPropertyInspectorPlugin.gd, demo/addons/fmod/tool/property_editors/FmodBankPathEditorProperty.gd, src/fmod_string_names.cpp, src/fmod_string_names.h, src/nodes/fmod_bank_loader.cpp, src/nodes/fmod_bank_loader.h, src/register_types.cpp
=> fix: Revert of banks in FmodBankLoader UI now works

.github/workflows/check_pr.yml
This changes godot download address to get rid of tuxfamily.org.
=> enh(ci): Change godot download address

SConstruct
=> fix: Set ios min version to 12

docs/src/doc/user-guide/5-playing-events.md
=> fix typos and update copyediting in Playing Events in documentation
