godot_fmod.h
Suppress the clang warning.
const does not have any effect in headers.
=> Fix_const_header : Remove const from methods declarations in header

godot_fmod.cpp
Hotfix, instance were not removed from maps for sounds and events.
Conformity with engine version.
=> HOTFIX-InstancesNotReleasedCorrectly: Done removing from maps

godot_fmod.cpp
Fix 3DAttributes in update loop for 2D objects.
This conform our repo to engine module version.
Candidate for 2.0.1 release
Do not delete the branch after merging. We need to release 2.0.1 before.
=> HOTFIX-3DAttributesFor2DNodes : Done fixing 3DAttributes for 2D nodes

.gitignore, src/godot_fmod.cpp, src/godot_fmod.h, src/helpers/containers.h
Load VCAs, buses, and event descriptions when loading banks.
Unload them when unloading bank.
Helper methods to check if vca, bus or event descriptions is valid according to banks loaded.
=> Load data when loading banks

README.md
At several places in the examples in the README.md, the code mentions `FmodF`
I assume that this is a typo as FmodF doesn't exist at all?
(At least not in my version of the demo project?)
=> Remove erroneous FmodF

demo/addons/fmod/Fmod.gdnlib
Path of Linux library in this file was:
`X11.64="res://addons/fmod/libs/linux/libGodotFmod.linux.so"`
But the file downloaded from the Releases has following name:
`libGodotFmod.linux.release.so`
Probably a left-over from testing?
=> Modify of Linux library to same path as in release

demo/addons/fmod/Fmod.tscn, demo/addons/fmod/fmod_singleton.gd, demo/project.godot
Implement #61 
The autoload is now a simple scene with the Fmod wrapper attached to the root node.
The test scene works normally and GUT doesn't return any failure so it seems to properly work.
=> Autoload is now a scene.

demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp
Fix #58 
The autoload wrapper now has a destructor that will free the GDNative instance. 
No leak should happen when the game is closing with this fix.
=> Add destructor to Fmod wrapper.

demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
Fix issue #60 
All exposed methods that previously used Object are now using Node as parameter/return type.
The node has to be either be a CanvasItem or a spatial, otherwise, an error is returned.
=> Change Object to Node and add additional type check.

README.md, demo/addons/fmod/Fmod.gd, demo/project.godot, demo/test/unit/test_ainit_fmod.gd, demo/test/unit/test_global.gd, src/godot_fmod.cpp, src/godot_fmod.h
As explained in https://github.com/utopia-rise/fmod-gdnative/issues/91 there is currently the issue on certain systems that the audio plays back with delay. The reason is that the default DSP buffer size has the wrong configuration.
This pull request allows to configure the DSP buffer size like so in Godot:
```gdscript
Fmod.set_dsp_buffer_size(512, 4)
Fmod.init(1024, Fmod.FMOD_STUDIO_INIT_LIVEUPDATE, Fmod.FMOD_INIT_NORMAL)
```
I tested this with my game and the audio playback latency is now near real-time. No more audible lag after setting this in my game code!
=> Add support for DSP buffer size

demo/addons/fmod/Fmod.gd, demo/test/unit/test_desc_event.gd
_addresses #103_
Add missing arguments to FMOD autoload methods.
=> :bug: add missing user property argument

demo/addons/fmod/nodes/FmodEventEmitter.gd
The existing logic of `FmodEventEmitter` would never preload event data, leading to lag when playing event information for the first time. This is due to the fact that loading a bank will only load its metadata but not sample data for individual events. By default, instantiating a new node of type `FmodEventEmitter` will now preload its sample data. This can be disabled in the export.
=> :sparkles: preload sample data by default

README.md, docs/COMPILING.md
This splits compiling documentation section in another markdown file.  
This should make readme more straightforward regarding how to install plugin.  
This resolves #80
=> Enhancement: split compiling and installing docs

.github/workflows/all_builds.yml, SConstruct, get_fmod.py, src/callback/file_callbacks.h
@bitbrain 
This ports Github Actions compilation for all platforms to be compatible with the new GDExtension.
I'm still having some issues with iOS, but I imagine it's related to FMOD having to update their binaries (?).
I'll see if I can port the automatic GUT and release stage as well at some point.
EDIT: I propose to merge this branch as soon as possible into godot-4.0-adaption such that we can detect any new compilation bugs and errors immediately and effortlessly.
=> Port all_builds.yml to be compatible to GDExtension

demo/Script/ChangeColor.gd, demo/Script/FmodTest.gd, demo/addons/fmod/Fmod.gd, src/godot_fmod.cpp, src/godot_fmod.h
=> Add default callback setting

src/godot_fmod.cpp, src/godot_fmod.h
While building the project, the following warning appears multiple times:
../godot-cpp/include/core/Godot.hpp:163:10: warning: returning reference to local temporary object [-Wreturn-stack-address]
return a;
^
../godot-cpp/include/core/Godot.hpp:285:34: note: in instantiation of member function 'godot::_ArgCast<const godot::Array &>::_arg_cast' requested here
*ret = (obj->*f)(_ArgCast<As>::_arg_cast(*args[I])...);
^
../godot-cpp/include/core/Godot.hpp:310:10: note: in instantiation of function template specialization 'godot::_WrappedMethod<godot::Fmod, float, unsigned long, const godot::Array &>::apply<0, 1>' requested here
method->apply(var, obj, arg, typename __construct_sequence<sizeof...(As)>::type{});
^
../godot-cpp/include/core/Godot.hpp:325:34: note: in instantiation of function …
=> fix return-stack-address violations

demo/high_level/ChangeColor.gd, demo/high_level/Emitter.gd, demo/high_level/FmodNodesTest.gd, demo/high_level/FmodNodesTest.tscn, demo/high_level/Kinematic.gd, demo/low_level/FmodNodesTest.tscn, demo/test/unit/test_event.gd, src/nodes/fmod_bank_loader.cpp, src/nodes/fmod_bank_loader.h, src/nodes/fmod_event_emitter.h, src/nodes/fmod_event_emitter_2d.cpp, src/nodes/fmod_event_emitter_2d.h, src/nodes/fmod_event_emitter_3d.cpp, src/nodes/fmod_event_emitter_3d.h, src/nodes/fmod_listener.h, src/nodes/fmod_listener_2d.cpp, src/nodes/fmod_listener_2d.h, src/nodes/fmod_listener_3d.cpp, src/nodes/fmod_listener_3d.h
This simplify emitters code using a CRTP.  
This brings back gdscript fmod event emitter we had in 3.x in cpp.  
Next steps are fmod nodes.  
I think we can merge `godot-4.x` in `master` when this one is merged.
=> fix: Fmod event emitter now works as in 3.x and code has been simplified

demo/addons/fmod/tool/inspectors/FmodEmitterPropertyInspectorPlugin.gd
`_parse_category` was returning early, preventing the instantiation of the editor property for FmodEventEmitter3D nodes.
=> Fix missing editor property for FmodEventEmitter3D nodes

src/fmod_server.cpp
=> fix: initialize fmod engine with right handed coordinates

src/nodes/fmod_event_emitter_3d.cpp
=> fix: use global transform as space attribute for FmodEventEmitter3D

demo/low_level_2D/Emitter.gd, src/nodes/fmod_event_emitter.h, src/nodes/fmod_listener.h
I discovered that functions like `_enter_tree(`) or`_process()` in gdextension are overridden by regular scripts.
When it's the case, the C++ code we wrote for nodes was no longer executed, leading to their positions no longer updated.
I no longer override those usual lifecycle callbacks anymore and rely on notifications instead.
`_notification()` is safe to override, Godot treats this method as a special case and call all implementations across native objects, extensions and scripts.
=> Fix node notifications and positions

demo/project.godot, src/helpers/maths.h
2D is a simple matter, we just have to (I hope) negate the values on X.
I added back the ability to rotate the listener in the 2D demos so we can make sure we hear the sound in the right direction when not facing upward (use the left and right arrow).
=> Fix 2D rotation

demo/addons/fmod/FmodManager.gd, demo/addons/fmod/tool/ui/EventParametersDisplay.gd, demo/addons/fmod/tool/ui/EventPlayControls.gd, demo/addons/fmod/tool/ui/FmodBankExplorer.gd, demo/addons/fmod/tool/ui/FmodBankExplorer.tscn, demo/addons/fmod/tool/ui/ParameterDisplay.gd, demo/addons/fmod/tool/ui/ParameterDisplay.tscn
- new design for the explorer based on #200 
- theme agnostic
- button strings replaced with icons
- adds playback controls
- play
- stop
- allow fade out
- adds a button to refresh the banks (unloads the current ones, loads new ones from directory specified in project settings)
=> Explorer redesign and event playback controls

src/fmod_cache.cpp, src/fmod_server.cpp, src/helpers/common.h, src/tools/fmod_editor_export_plugin.cpp
Simple change to make the plugin quieter when Godot is not in verbose mode. In that case, it should only print the initialization of the system. Logs for loading files and banks are now verbose.
=> Add verbose print

demo/high_level_2D/ChangeColor.gd, demo/high_level_2D/FmodNodesTest.tscn, demo/high_level_2D/Kinematic.gd, demo/low_level_2D/FmodTest.gd, demo/low_level_2D/Listener.gd, src/fmod_server.cpp, src/fmod_server.h, src/nodes/fmod_event_emitter.h, src/nodes/fmod_event_emitter_2d.cpp, src/nodes/fmod_event_emitter_2d.h, src/nodes/fmod_event_emitter_3d.cpp, src/nodes/fmod_event_emitter_3d.h
It had previously leftovers from the implementation in Godot 3.x (all events, not only oneshots were managed by the server) so I got rid of them.
A oneshot is actually not something up to the Godot user to decide, it's a property of the Fmod event itself, I removed its setter from the FmodEmitter node.
On top of that, only oneshot events can now be used as such. If not, a warning will be thrown. The reason for this is that one shot events can actually end (unlike the ones designed to loop), otherwise they would continue playing forever without any way to stop them. 
The methods to play a one shot won't ask for a Node if not attached.
Because emitters can no longer be set as oneshot, I replaced it with an auto release feature. When the event is done playing, the node will automatically …
=> Fix OneShot system.

src/fmod_server.cpp
The last explorer update changed the FmodManager.gd into a tool script, allowing FmodServer to be updated and play event previews.
It had the side effects of adding a warning message, when starting the editor, complaining that no listener is set. 
I simply added a condition that will prevent listener (and performance data as well, because we only want them from a remote instance) to be updated by the FmodServer.
=> Remove listener update when in editor

src/fmod_server.cpp, src/fmod_server.h
This fixes #186 
This adds methods to set global parameters value by label in `FmodServer`.  
This enables to use `play_one_shot` methods with parameters values being either float or labels.
=> feat: add methods to set parameters by label in FmodServer

.github/actions/create-android-plugin/action.yaml, .github/actions/create-native-build/action.yaml, .github/workflows/check_pr.yml, .github/workflows/release.yml, android-plugin/library/build.gradle.kts
This updates plugin to godot `4.2.2`.
=> chore: update to godot 4.2.2

demo/addons/fmod/tool/property_editors/FmodEventEditorProperty.gd, src/fmod_cache.cpp, src/nodes/fmod_event_emitter.h
=> fix: avoid crash when event is not found by guid or path

.github/actions/create-android-plugin/action.yaml, .github/actions/create-native-build/action.yaml, .github/workflows/check_pr.yml, .github/workflows/release.yml, android-plugin/library/build.gradle.kts, demo/.godot/editor/project_metadata.cfg, demo/project.godot, src/helpers/common.h, src/nodes/fmod_event_emitter.h, src/nodes/fmod_listener.h
- updates `godot-cpp` to `godot-4.3-stable` branch
- various fixes to make this codebase compatible with new changes
=> Update to Godot 4.3

demo/test/unit/test_bank.gd, demo/test/unit/test_bus.gd, demo/test/unit/test_callbacks.gd, demo/test/unit/test_desc_event.gd, demo/test/unit/test_event.gd, demo/test/unit/test_global.gd, demo/test/unit/test_listener.gd, demo/test/unit/test_vca.gd, src/fmod_server.cpp, src/fmod_server.h, src/nodes/fmod_listener.h
This resolves #252 by addign `Object*` parameter to `FmodServer::remove_listener` to check if same object before removing listener.
=> fix: Check object before removing listener

demo/high_level_2D/SayWelcomeButton.gd, src/fmod_cache.cpp, src/fmod_cache.h, src/fmod_server.cpp, src/fmod_server.h, src/nodes/fmod_event_emitter.h, src/studio/fmod_event.cpp, src/studio/fmod_event.h, src/studio/fmod_event_description.cpp, src/studio/fmod_event_description.h
When event GUID is set, it will also set event_name, reverse is also true.
When event guid or name is set it stop current event and start the new one, it also clear parameters.
`auto_release` is now only for releasing node, not event. Event is automatically released.
If event has finished playing and emitter is autoplay, it will play again the event (enable play loop)
=> enh: Simplify emitter event playing

.github/actions/create-native-build/action.yaml, .github/workflows/check_pr.yml, .github/workflows/release.yml, SConstruct, demo/addons/fmod/.gitignore, demo/addons/fmod/fmod.gdextension
This adds ios xcframework build to CI according to https://github.com/godotengine/godot/issues/90168
=> fix: Add ios xcframework build to CI

src/fmod_cache.cpp, src/fmod_cache.h
This avoid crash when fetching wrong bus or vca.
=> fix: Avoid crash when fetching wrong bus or vca

demo/addons/fmod/FmodManager.gd, demo/addons/fmod/tool/performances/PerformancesDisplay.gd
=> fix: Remove performance monitor on exit to avoid crash

src/nodes/fmod_listener.h
There was a mistake in listener's index property registration preventing it from being registered in scene: it was in editor usage.  
This resolves #291
=> fix: set FmodListener's index property usage to default

src/tools/fmod_editor_export_plugin.cpp
=> fix: Do not include android build dir in export

SConstruct, src/fmod_string_names.cpp, src/fmod_string_names.h, src/nodes/fmod_event_emitter.h
This resolves #293 
There was a problem when duplicating emitters, it was trying to call `_get` and `_set` on `fmod_parameters` root.
=> fix: Avoid to get and set fmod_parameters root

demo/addons/fmod/tool/property_editors/FmodEventEditorProperty.gd
=> fix: do not allow read-only and automatic parameters in event emitters

src/nodes/fmod_event_emitter.h
We were returning a pointer to a non godot type in `FmodEventEmitter::get_parameter` methods, which was converted to a bool.  
This returns the actual value of parameter.
=> fix: return parameter value in emitter's get_parameter methods

src/fmod_server.cpp
Setting FMOD's Advanced Settings's random seed to system time.
=> enh: sets the FMOD random seed to system time before initialization (#273)

.github/workflows/check_pr.yml, .github/workflows/release.yml, src/fmod_server.cpp, src/fmod_server.h, src/helpers/common.h, src/studio/fmod_event.cpp
Fix #301
In several parts of FmodServer, we were using Godot objects that could have potentially died since the previous iteration:
- The listeners
- The oneshots
- The callbacks
We normally use the ObjectID to fetch the validity of those objects but we assume the ID was stored locally in the wrapper. In fact it wasn't so everytime we wanted to use it and the object was dead, we were using a dead pointer, hence the crash.
=> Check Node validity using locally stored ObjectID

demo/addons/fmod/plugin.cfg
A very small fix 🙂 to keep the plugin version up to date.
I'm actually reading it out in a small script to install the dependencies for the devs in my team, so I actually depend on this.
=> Increase plugin config version to match the current tag 6.0.0

src/callback/file_callbacks.cpp, src/callback/file_callbacks.h
During the investigation regarding #351, I came across minor improvements for the file callback so it's more in line with what FMOD expects ( using their own examples as reference).
They don't fix the issue because the cause is unrelated but I'm still pushing them so we avoid any weird minor side effects in the future:
- Fmod has 3 priorities 0, 50, 100. I moved 50 to be considered "High priority"
- Godot "end of file" returns true when we exactly reach the end of a file, but FMOD only wants to know when we got beyond it (hence checking if the returned size is smaller than the one required).
- Cancel request have to call "done" to confirm they were indeed cancelled.
=> Improve file callback

src/helpers/files.h, src/resources/fmod_plugins_settings.cpp
I think that's the crash encountered on #360 
We were not checking if a directory exists in `list_files_in_folder` method. So if the user has no plugins settings set or the path in its settings does not exists it crashes.
=> fix: Check directory exists before listing files in it

src/nodes/fmod_event_emitter.h
During export, Godot Engine itself can experience a crash due to this extension in case some of the FMOD events are incorrectly set up inside the editor. The current implementation assumes that the editor always is set up correctly, however, there can be situations where it isn't.
Note: ideally, during export, we should also show warnings to the user for any event that we could not resolve properly (which currently does not yet happen) but I am looking into a separate PR for this.
=> Fix rare crash during export when FMOD events are incorrectly setup by user

src/tools/fmod_editor_export_plugin.cpp, src/tools/fmod_editor_export_plugin.h
This change adds an option per Godot export preset to enable or disable exporting the banks automatically. Exporting is enabled by default so it doesn't change anything for existing configurations.
I believe this improves workflows under certain conditions especially in projects with multiple export plugins and/or multiple export presets for the same project.
=> feat: enable / disable banks exporting per Godot export preset
